-- ✅ WORKING SEED - Milwaukee Canvas V2 with Proper Newlines
-- Copy this ENTIRE file and paste into Supabase SQL Editor

DELETE FROM lessons WHERE id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11';

INSERT INTO lessons (id, title, description, category, difficulty, estimated_minutes, xp_reward, target_roles, is_public, content_json)
VALUES (
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  'Milwaukee Application First Canvas - Mapa Rozmowy',
  'Standardowa 7-krokowa mapa rozmowy JSS: od aplikacji do demo i domknięcia.',
  'Milwaukee',
  'advanced',
  90,
  200,
  ARRAY['sales', 'jss', 'field'],
  true,
  jsonb_build_object(
    'cards', jsonb_build_array(
      jsonb_build_object('id', 1, 'type', 'intro', 'title', 'Application First - Mapa Rozmowy', 'subtitle', 'Standard rozmowy, demo i domknięcia w Milwaukee', 'description', E'7-krokowa struktura prowadzenia wizyty w terenie - bez slajdów, tylko praktyka.\n\n**💡 Filozofia Application First**\n\nRozwiązujesz **PRACĘ**, nie prezentujesz **NARZĘDZIE**', 'icon', 'Map'),
      jsonb_build_object('id', 2, 'type', 'intro', 'title', 'Dla kogo jest ta lekcja?', 'description', E'**🔧 JSS (Job-Site Solution Specialist)**\n\n**Rola terenowa, konsultacyjna:**\n\n* Pracujesz w środowisku użytkownika\n* Diagnozujesz realną pracę\n* Demo aplikacyjne na miejscu\n* Domykasz konkretnymi krokami', 'icon', 'Users'),
      jsonb_build_object('id', 3, 'type', 'concept', 'title', 'Case Study: Dwie wizyty', 'content', E'**Scenariusz:** Montaż instalacji wentylacyjnej - 200-300 śrub M8 dziennie, 2-osobowa ekipa\n\n### ❌ WIZYTA #1 - Klasyczna (Jak NIE robić)\n\n**JSS Marek:**\n"Mam wiertarkę M18 FUEL. Promocja! 135 Nm, bezszczotkowy silnik..."\n\n**Brygadzista:**\n"Mamy Dewalt."\n\n**Rezultat:** "Zostaw katalog."\n\n**Co poszło nie tak?**\n* ❌ Start od produktu\n* ❌ Brak diagnozy\n* ❌ Demo "na ślepo"\n* ❌ Język techniczny\n* ❌ Brak domknięcia'),
      jsonb_build_object('id', 4, 'type', 'concept', 'title', 'Case Study: Application First Success', 'content', E'### ✅ WIZYTA #2 - Application First (Jak NALEŻY)\n\n**JSS Kasia:**\n"Jak wygląda ta praca? Ile takich połączeń dziennie?"\n\n**Brygadzista:**\n"200-300 śrub. Wiertarka się przegrzewa po godzinie."\n\n**JSS Kasia (KROK 3):**\n"Ile czasu tracisz na czekanie?"\n\n**Brygadzista:**\n"30-40 minut dziennie."\n\n**Rezultat po demo:**\nTest tygodniowy, spotkanie piątek 10:00, **80%+ szans na decyzję**!', 'xp', 20),
      jsonb_build_object('id', 5, 'type', 'concept', 'title', '7 Kroków Mapy Canvas', 'content', E'## 📋 Canvas = Mapa rozmowy JSS\n\n**Każdy krok ma cel, pytania i kryterium sukcesu:**\n\n1. **Aplikacja** - Zrozumieć realną pracę\n2. **Problem** - Wydobyć pain points\n3. **Konsekwencje** - Kwantyfikacja (czas/koszt)\n4. **Rozwiązanie** - System Milwaukee (3 elementy)\n5. **Demo** - Z celem i kryterium sukcesu\n6. **Wartość** - Język klienta (SAM kalkuluje)\n7. **Next Steps** - KTO-CO-KIEDY + follow-up 24h'),
      jsonb_build_object('id', 6, 'type', 'question', 'question', 'Która wizyta miała większą szansę na sukces?', 'options', jsonb_build_array('Wizyta #1 (Marek) - szybka prezentacja produktu', 'Wizyta #2 (Kasia) - Application First Canvas', 'Obie miały podobne szanse', 'Żadna - klient i tak nie chciał kupować'), 'correctAnswer', 1, 'explanation', 'Wizyta Kasi wykorzystała Application First Canvas: diagnoza pracy → pain point → konsekwencje → demo z celem → wartość językiem klienta → konkretne next steps.', 'xp', 15),
      jsonb_build_object('id', 7, 'type', 'concept', 'title', 'KROK 1: Aplikacja (Job to be Done)', 'content', E'## 🎯 Cel KROKU 1\n\nZrozumieć **REALNĄ PRACĘ** klienta:\n* Środowisko (warunki)\n* Częstotliwość (jak często?)\n* Skala (ile osób? ile operacji?)\n* Wyzwania (co najtrudniejsze?)\n\n### Przykładowe pytania JSS:\n\n* "Jak często robisz tę pracę?"\n* "W jakich warunkach?"\n* "Co najtrudniejsze w tej czynności?"\n* "Ile osób robi tę pracę?"\n* "Jak długo trwa jedna operacja?"\n\n**⚠️ UWAGA:** W KROKU 1 **NIE MOŻESZ** mówić o produkcie!\n\nTwoja rola: **słuchać, pytać, obserwować**'),
      jsonb_build_object('id', 8, 'type', 'practice', 'title', 'Ćwiczenie: Role Play - KROK 1', 'content', E'**Scenariusz:** JSS odwiedza warsztat samochodowy. Mechanik robi pracę przy zawieszeniu (zardzewiałe śruby M12-M16).\n\n### 📋 Zasady:\n* ⏱️ Czas: 3 minuty\n* 🎯 Cel: Zdiagnozować aplikację\n* ❌ Zakaz: NIE możesz mówić o produkcie Milwaukee\n* ✅ Dozwolone: Pytania otwarte o pracę\n\n### Twoje zadanie:\n\nZadaj minimum **5 pytań**, które pomogą zrozumieć:\n1. Jak często odkręca zardzewiałe śruby?\n2. W jakich warunkach?\n3. Jakie narzędzia teraz używa?\n4. Co najtrudniejsze?\n5. Ile czasu to zabiera dziennie?', 'xp', 25),
      jsonb_build_object('id', 9, 'type', 'question', 'question', 'Co JSS robi w KROKU 1 (Aplikacja)?', 'options', jsonb_build_array('Pokazuje katalog produktów Milwaukee', 'Pyta o pracę i warunki, obserwuje środowisko', 'Robi demo narzędzi', 'Przedstawia ofertę cenową'), 'correctAnswer', 1, 'explanation', 'W KROKU 1 JSS zadaje pytania o Job to be Done - realną pracę klienta. NIE mówi o produkcie, tylko słucha i obserwuje.', 'xp', 15),
      jsonb_build_object('id', 10, 'type', 'concept', 'title', 'KROK 2: Pain Points (Problem)', 'content', E'## ⚠️ Złota zasada KROKU 2\n\n**"Jeśli klient nie nazwie problemu - nie ma decyzji"**\n\n### 4 kategorie Pain Points:\n\n* 🤕 **Ergonomia** - "Jak się czujesz po całym dniu?"\n* ⏱️ **Czas** - "Ile czasu to zabiera? Czy są przestoje?"\n* 🛡️ **Bezpieczeństwo** - "Czy zdarzają się wypadki?"\n* 💰 **Koszt** - "Ile kosztuje przestój?"\n\n### ❌ ŹLE - JSS sugeruje:\n\n"Widzę, że Pana narzędzie jest ciężkie. Na pewno boli nadgarstek?"\n\n### ✅ DOBRZE - JSS pyta:\n\n"Jak się Pan czuje po całym dniu takiej pracy?"\n\n**Klient SAM mówi:** "Nadgarstki mnie zabijają. Po 4-5h muszę robić przerwę."'),
      jsonb_build_object('id', 11, 'type', 'concept', 'title', 'KROK 3: Konsekwencje (Impact)', 'content', E'## 📊 Kwantyfikacja\n\n**Problem → Konsekwencje**\n\nKlient mówi: "Nadgarstki bolą"\n\n**JSS pyta:** "Ile razy dziennie robisz przerwę?"\n\n**Klient:** "2-3 razy po 15 min"\n\n**Kwantyfikacja:**\n* ⏱️ **30-45 min/dzień stracone**\n* 📅 3-4h/tydzień\n* 📊 12-16h/miesiąc\n\n**💡 Kluczowa technika:**\n\nJSS **NIE kalkuluje sam**. Zadajesz pytania i klient **SAM przelicza** konsekwencje!'),
      jsonb_build_object('id', 12, 'type', 'question', 'question', 'Co JSS robi w KROKU 3 (Konsekwencje)?', 'options', jsonb_build_array('Kalkuluje ROI w Excelu i pokazuje klientowi', 'Pyta ''Ile to kosztuje?'' - klient SAM kwantyfikuje', 'Przechodzi od razu do demo produktu', 'Mówi o konkurencji'), 'correctAnswer', 1, 'explanation', 'JSS zadaje pytania typu ''Ile to kosztuje?'' aby klient SAM przeliczył konsekwencje (czas/koszt). To buduje ownership decyzji!', 'xp', 15),
      jsonb_build_object('id', 13, 'type', 'concept', 'title', 'KROK 4: Rozwiązanie Systemowe', 'content', E'## 🧩 System = 3 elementy\n\n### 1️⃣ Narzędzie bazowe (adresuje pain point)\n\nPrzykład: Problem "przegrzewanie" → wiertarka FUEL bezszczotkowa\n\n### 2️⃣ Baterie + ładowarka (wydajność)\n\nMinimum **2-4 baterie** (rotacja - zawsze jedna naładowana)\n\nPrzykład: 4 baterie 5.0 Ah + szybka ładowarka 6-port\n\n### 3️⃣ Akcesoria specjalistyczne\n\nPrzykład: Wiertła HSS-G Thunderweb (żywotność 2x dłuższa)\n\n---\n\n## ❌ PRODUKT vs ✅ SYSTEM\n\n**Produkt:**\n"M18 FUEL. 135 Nm, bezszczotkowy..."\n\n**System:**\n"M18 FUEL + 4 baterie + ładowarka = rozwiązuje przegrzewanie i przestoje"'),
      jsonb_build_object('id', 14, 'type', 'concept', 'title', 'KROK 5: Demo Aplikacyjne', 'content', E'## 🎬 3 elementy demo\n\n### 1. Co sprawdzamy? (Cel)\n\n"Sprawdzimy, czy system Milwaukee pozwoli Ci pracować **bez przerw przez 2 godziny**"\n\n### 2. Na co patrzymy? (Kryterium sukcesu)\n\n"Zrobimy **100 otworów M12**. Jeśli nie przegrzeje się - wiemy, że działa"\n\n### 3. Klient pracuje! (Nie JSS pokazuje)\n\n"Proszę spróbować - niech Pan zrobi 10 otworów swoją metodą"\n\n---\n\n## 🚫 3 błędy w demo:\n\n* ❌ #1: **Pokaz cyrkowy** - JSS robi, klient patrzy\n* ❌ #2: **Bez celu** - pokazuję bo mam\n* ❌ #3: **Na szybko** - 5 minut nie testuje realnej pracy'),
      jsonb_build_object('id', 15, 'type', 'question', 'question', 'Które stwierdzenie o demo jest PRAWDZIWE?', 'options', jsonb_build_array('JSS robi demo sam - klient patrzy i ocenia', 'Demo bez celu - ''pokazuję bo mam narzędzie''', 'Demo ma cel, kryterium sukcesu i klient SAM pracuje', 'Demo powinno być krótkie (5 min) żeby nie nudzić'), 'correctAnswer', 2, 'explanation', 'Demo aplikacyjne ma: CEL (co sprawdzamy?), KRYTERIUM SUKCESU (na co patrzymy?) i użytkownik w roli głównej (klient SAM pracuje).', 'xp', 20),
      jsonb_build_object('id', 16, 'type', 'practice', 'title', 'Ćwiczenie: Budowanie systemu', 'content', E'**Scenariusz:** Klient (dekarz) montuje pokrycia dachowe. Pain point: "Wkrętarka się przegrzewa po 2h intensywnej pracy."\n\n### Twoje zadanie:\n\n1. **Zbuduj rozwiązanie systemowe** (3 elementy)\n2. **Uzasadnij każdy element** - jak rozwiązuje przegrzewanie?\n3. **Zaproponuj demo** z celem i kryterium sukcesu\n\n### Szablon:\n\n**Narzędzie bazowe:** _______\n**Baterie + ładowarka:** _______\n**Akcesoria:** _______\n\n**Cel demo:** _______\n**Kryterium sukcesu:** _______', 'xp', 30),
      jsonb_build_object('id', 17, 'type', 'concept', 'title', 'KROK 6: Wartość (język klienta)', 'content', E'## 💎 3 pytania wydobywające wartość\n\n### 1. "Co się zmieniło?"\n\n**Klient:** "Naprawdę nie przegrzało się. Nie musiałem robić przerwy."\n\n### 2. "Co jest teraz łatwiejsze?"\n\n**Klient:** "Nie boli ręka jak poprzednio. Mogę pracować dłużej."\n\n### 3. "Jak to wpływa na Twoją pracę?"\n\n**Klient:** "Oszczędzam te 30-40 minut dziennie. Przy 15 dniach do deadline to **prawie cały dzień roboczy**. Zdążymy bez nadgodzin."\n\n---\n\n**💡 Kluczowa zasada:**\n\nJSS **NIE kalkuluje wartości sam**. Klient **SAM** przelicza i **SAM** mówi o korzyściach!'),
      jsonb_build_object('id', 18, 'type', 'concept', 'title', 'KROK 7: Next Steps (Domknięcie)', 'content', E'## ✅ KTO-CO-KIEDY\n\n### 1. KTO (Decydent)\n\n"Rozumiem - Pan testuje, ale decyzję podejmuje kierownik budowy. Czy możemy umówić się razem na piątek?"\n\n### 2. CO (Konkretne działanie)\n\n"Zostawiam system na **tydzień testowy**. Pan testuje normalnie. W piątek porozmawiamy o wynikach."\n\n### 3. KIEDY (Data i godzina)\n\n"Wrócę w **piątek 10:00**. Będzie Pan wtedy? Dobrze, to do piątku."\n\n---\n\n## 📧 Follow-up 24h\n\nPo wizycie JSS wysyła email/SMS podsumowujący **wszystkie 7 kroków Canvas**.'),
      jsonb_build_object('id', 19, 'type', 'practice', 'title', 'Ćwiczenie: Follow-up email', 'content', E'**Scenariusz:** Po wizycie na budowie (brygadzista - montaż instalacji). Ustaliliście:\n\n* Problem: Baterie kończą się po 40-50 połączeń\n* Demo: System M18 FPP + 6 baterii wytrzymał 200 połączeń\n* Wartość (słowa klienta): "To oszczędność 20-30h miesięcznie!"\n* Next Steps: Test 2-tygodniowy, spotkanie 22.12 o 9:00\n\n### Napisz follow-up email zawierający:\n\n1. Wszystkie 7 kroków Canvas\n2. Cytaty klienta z KROKU 6\n3. Konkretne Next Steps (22.12 o 9:00)', 'xp', 25),
      jsonb_build_object('id', 20, 'type', 'question', 'question', 'Czym jest KROK 7 (Next Steps)?', 'options', jsonb_build_array('Podpisanie umowy i zapłata', 'Ustalenie ''kto-co-kiedy'' + konkretne zobowiązania', 'Pożegnanie ''proszę pomyśleć''', 'Wysłanie katalogu emailem'), 'correctAnswer', 1, 'explanation', 'KROK 7 to domknięcie konkretne: KTO-CO-KIEDY. Przykład: ''Test tygodniowy, wrócę piątek o 10:00, wtedy oferta'' + follow-up 24h!', 'xp', 15),
      jsonb_build_object('id', 21, 'type', 'concept', 'title', 'Produktowa vs Application First', 'content', E'## Porównanie podejść\n\n### ❌ WIZYTA PRODUKTOWA\n\n* Start od produktu\n* Brak diagnozy\n* Demo "na ślepo"\n* Język techniczny\n* Brak domknięcia\n\n**Rezultat:** "Zostaw katalog, pomyślimy"\n\n---\n\n### ✅ WIZYTA APPLICATION FIRST\n\n* Start od aplikacji (Job to be Done)\n* Diagnoza pain points\n* Demo z celem i kryterium\n* Język klienta (wartość)\n* Domknięcie KTO-CO-KIEDY\n\n**Rezultat:** Test/oferta + konkretny follow-up'),
      jsonb_build_object('id', 22, 'type', 'question', 'question', 'Jakie jest największe ryzyko wizyt PRODUKTOWYCH?', 'options', jsonb_build_array('Zbyt długa wizyta (ponad 2 godziny)', 'Start od produktu - brak diagnozy = brak decyzji', 'Za dużo pytań do klienta', 'Demo za długie'), 'correctAnswer', 1, 'explanation', 'Wizyty produktowe tracą bo: brak diagnozy aplikacji, brak pain pointów, demo ''na ślepo'', brak wartości w języku klienta. Rezultat: ''zostaw katalog'' = koniec.', 'xp', 20),
      jsonb_build_object('id', 23, 'type', 'practice', 'title', 'Ćwiczenie: Przerobienie wizyty', 'content', E'**Błędna wizyta Tomka:**\n\nTomek: "Mam pilarki M18. Promocja - 1899 zł!"\nStolarz: "Mamy DeWalt."\nTomek: "Ale Milwaukee ma lepsze parametry!"\nStolarz: "Zostaw katalog."\n\n### Twoje zadanie:\n\n**Przepisz wizytę** według Application First Canvas (7 kroków):\n\n1️⃣ Aplikacja: _______\n2️⃣ Pain Points: _______\n3️⃣ Konsekwencje: _______\n4️⃣ Rozwiązanie: _______\n5️⃣ Demo: _______\n6️⃣ Wartość: _______\n7️⃣ Next Steps: _______', 'xp', 30),
      jsonb_build_object('id', 24, 'type', 'concept', 'title', 'Kluczowe wnioski', 'content', E'## 📚 Zapamiętaj:\n\n* ✓ **Start od aplikacji** (Job to be Done), nie od produktu\n* ✓ **Klient SAM nazywa problem** (nie sugerujesz)\n* ✓ **Klient SAM kwantyfikuje** konsekwencje\n* ✓ **System = 3 elementy** (narzędzie + baterie + akcesoria)\n* ✓ **Demo z celem** i kryterium sukcesu\n* ✓ **Klient SAM kalkuluje wartość** (nie JSS na siłę)\n* ✓ **Domknięcie: KTO-CO-KIEDY** + follow-up 24h\n\n---\n\n**💡 Application First Canvas = sposób myślenia o wizycie**\n\nTo nie "technika sprzedaży" - to **mapa rozmowy JSS**'),
      jsonb_build_object('id', 25, 'type', 'practice', 'title', 'Action Plan', 'content', E'## 🎯 Co robisz TERAZ?\n\n### 📅 DZIŚ (15 minut po lekcji)\n\n_Wydrukuj checklist Canvas, zapisz w telefonie 3 kluczowe pytania z KROKU 1_\n\n### 🎯 JUTRO (Pierwsze zastosowanie)\n\n_Na wizycie u klienta X zacznę od KROKU 1 - pytania o aplikację zamiast prezentacji_\n\n### ⏰ ZA TYDZIEŃ (Review + powtórka)\n\n_Wrócę do quizu, przejrzę fiszki, porównam moje wizyty z checklistą_\n\n---\n\n**💡 Implementation Intention:**\n\nOsoby wypełniające Action Plan mają **+60% szans** na zastosowanie wiedzy w praktyce!'),
      jsonb_build_object('id', 26, 'type', 'summary', 'title', 'Canvas ukończony!', 'recap', jsonb_build_array('Opanowałeś 7-krokową Mapę Application First', 'Znasz różnicę między wizytą produktową a Application First', 'Potrafisz prowadzić demo z celem i kryterium sukcesu', 'Wiesz jak domykać wizytę: KTO-CO-KIEDY + follow-up 24h', '+200 XP zdobyte - jesteś gotowy na praktykę w terenie!'), 'nextSteps', 'Pobierz Cheatsheet, wróć za 3 dni do powtórki, zagraj w Business Games', 'badge', jsonb_build_object('xp', 200, 'title', 'Application First Specialist'))
    )
  )
);
