'use client'

import React, { useState, useEffect } from 'react'

interface SqlExportModalProps {
    cards: any[]
    onClose: () => void
}

export default function SqlExportModal({ cards, onClose }: SqlExportModalProps) {
    const [metadata, setMetadata] = useState({
        lesson_id: 'lesson_new_id',
        title: 'New Lesson Title',
        description: 'Lesson description...',
        difficulty: 'intermediate',
        duration: 20,
        xp: 300
    })

    const [sql, setSql] = useState('')

    useEffect(() => {
        generateSql()
    }, [metadata, cards])

    const generateSql = () => {
        // Construct the JSON object
        const contentJson = {
            cards: cards.map(c => {
                // Remove internal editor fields if needed, or keep for simplicity
                return c
            })
        }

        // Stringify and escape single quotes for SQL
        // The most critical part: ' becomes ''
        const jsonString = JSON.stringify(contentJson, null, 2).replace(/'/g, "''")

        const script = `-- SQL Script for Lesson: ${metadata.title}
-- Generated by BrainVenture Lesson Editor

-- 1. Cleanup old version
DELETE FROM lessons WHERE lesson_id = '${metadata.lesson_id}';

-- 2. Insert new version
INSERT INTO lessons (
    id,
    lesson_id,
    title,
    description,
    difficulty,
    duration_minutes,
    xp_reward,
    content
) VALUES (
    gen_random_uuid(),
    '${metadata.lesson_id}',
    '${metadata.title}',
    '${metadata.description.replace(/'/g, "''")}',
    '${metadata.difficulty}',
    ${metadata.duration},
    ${metadata.xp},
    '${jsonString}'::jsonb
);`

        setSql(script)
    }

    const copyToClipboard = () => {
        navigator.clipboard.writeText(sql)
        alert('Copied to clipboard!')
    }

    return (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/80 backdrop-blur-sm">
            <div className="bg-[#1a1a24] border border-white/10 rounded-xl w-[800px] h-[90vh] flex flex-col shadow-2xl">
                <div className="p-6 border-b border-white/10 flex justify-between items-center bg-[#111118] rounded-t-xl">
                    <h2 className="text-xl font-bold text-white">Export Lesson SQL</h2>
                    <button onClick={onClose} className="text-gray-400 hover:text-white">✕</button>
                </div>

                <div className="p-6 overflow-y-auto space-y-6 flex-1">
                    {/* Metadata Form */}
                    <div className="grid grid-cols-2 gap-4">
                        <div className="col-span-2">
                            <label className="text-xs uppercase text-gray-500 block mb-1">Lesson ID (Unique)</label>
                            <input
                                value={metadata.lesson_id}
                                onChange={e => setMetadata({ ...metadata, lesson_id: e.target.value })}
                                className="w-full bg-black/20 border border-white/10 rounded p-2 text-white font-mono text-sm"
                            />
                        </div>
                        <div className="col-span-2">
                            <label className="text-xs uppercase text-gray-500 block mb-1">Title</label>
                            <input
                                value={metadata.title}
                                onChange={e => setMetadata({ ...metadata, title: e.target.value })}
                                className="w-full bg-black/20 border border-white/10 rounded p-2 text-white"
                            />
                        </div>
                        <div className="col-span-2">
                            <label className="text-xs uppercase text-gray-500 block mb-1">Description</label>
                            <input
                                value={metadata.description}
                                onChange={e => setMetadata({ ...metadata, description: e.target.value })}
                                className="w-full bg-black/20 border border-white/10 rounded p-2 text-white"
                            />
                        </div>
                        <div>
                            <label className="text-xs uppercase text-gray-500 block mb-1">Duration (min)</label>
                            <input
                                type="number"
                                value={metadata.duration}
                                onChange={e => setMetadata({ ...metadata, duration: parseInt(e.target.value) })}
                                className="w-full bg-black/20 border border-white/10 rounded p-2 text-white"
                            />
                        </div>
                        <div>
                            <label className="text-xs uppercase text-gray-500 block mb-1">XP Reward</label>
                            <input
                                type="number"
                                value={metadata.xp}
                                onChange={e => setMetadata({ ...metadata, xp: parseInt(e.target.value) })}
                                className="w-full bg-black/20 border border-white/10 rounded p-2 text-white"
                            />
                        </div>
                    </div>

                    {/* SQL Output */}
                    <div>
                        <label className="text-xs uppercase text-[#00ff88] block mb-2 font-bold">Generated SQL Script</label>
                        <textarea
                            value={sql}
                            readOnly
                            className="w-full h-[300px] bg-black border border-white/10 rounded p-4 text-green-400 font-mono text-xs focus:outline-none"
                        />
                    </div>
                </div>

                <div className="p-6 border-t border-white/10 bg-[#111118] rounded-b-xl flex justify-end gap-3">
                    <button
                        onClick={onClose}
                        className="px-4 py-2 rounded bg-white/5 hover:bg-white/10 text-white transition-colors"
                    >
                        Cancel
                    </button>
                    <button
                        onClick={copyToClipboard}
                        className="px-4 py-2 rounded bg-[#00ff88] hover:bg-[#00cc66] text-black font-bold transition-colors shadow-[0_0_15px_rgba(0,255,136,0.3)]"
                    >
                        Copy SQL to Clipboard
                    </button>
                </div>
            </div>
        </div>
    )
}
